---
- name: Ensure Flink Group
  group:
    name: "{{ flink_group }}"
    gid: "{{ flink_gid }}"


- name: Ensure Flink User
  user:
    name: "{{ flink_user }}"
    group: "{{ flink_group }}"
    uid: "{{ flink_uid }}"
    home: /bin/false
    create_home: false
    comment: "Apache Flink"


- name: Check Flink Version
  command: bash -c "ls {{ flink_install_path }}/lib | grep 'flink-.*_{{ flink_scala_version }}-{{ flink_version }}.jar'"
  register: flink_check
  changed_when: false
  ignore_errors: true
  args:
    chdir: "{{ flink_install_path }}/bin"


- name: Install Flink
  block:
    - name: Delete Installation Older
      file:
        path: "{{ flink_install_path }}"
        state: absent

    - name: Create Install Path
      file:
        path: "{{ flink_install_path }}"
        state: directory
        owner: "{{ flink_user }}"
        group: "{{ flink_group }}"
        mode: 0755

    - name: Untar Flink
      unarchive:
        extra_opts: ['--strip-components=1']
        src: "{{ flink_mirror + flink_bin_url }}"
        remote_src: true
        dest: "{{ flink_install_path }}"
        owner: "{{ flink_user }}"
        group: "{{ flink_group }}"
      register: flink_download
      ignore_errors: true

    - name: Untar Flink By Archive
      unarchive:
        extra_opts: ['--strip-components=1']
        src: "{{ flink_mirror_archive + flink_bin_url }}"
        remote_src: true
        dest: "{{ flink_install_path }}"
        owner: "{{ flink_user }}"
        group: "{{ flink_group }}"
      when: 'flink_download is failed'

  when: 'flink_force_reinstall or flink_check is failed or flink_check.stdout|length == 0'


